"""timezone_added

Revision ID: 1a036866f88c
Revises: edab547e42dc
Create Date: 2023-01-30 02:19:05.335236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a036866f88c'
down_revision = 'edab547e42dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
