"""projects_created

Revision ID: edab547e42dc
Revises: 
Create Date: 2023-01-29 18:47:14.079783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edab547e42dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('client_full_name', sa.String(length=250), nullable=False),
    sa.Column('time_from', sa.DateTime(), nullable=False),
    sa.Column('time_to', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    op.create_index(op.f('ix_appointments_appointment_id'), 'appointments', ['appointment_id'], unique=False)
    op.create_table('specializations',
    sa.Column('specialization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('specialization_id')
    )
    op.create_index(op.f('ix_specializations_specialization_id'), 'specializations', ['specialization_id'], unique=False)
    op.create_table('doctors',
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=250), nullable=False),
    sa.Column('specialization_id', sa.Integer(), nullable=False),
    sa.Column('appointments_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['appointments_id'], ['appointments.appointment_id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['specialization_id'], ['specializations.specialization_id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('doctor_id')
    )
    op.create_index(op.f('ix_doctors_doctor_id'), 'doctors', ['doctor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doctors_doctor_id'), table_name='doctors')
    op.drop_table('doctors')
    op.drop_index(op.f('ix_specializations_specialization_id'), table_name='specializations')
    op.drop_table('specializations')
    op.drop_index(op.f('ix_appointments_appointment_id'), table_name='appointments')
    op.drop_table('appointments')
    # ### end Alembic commands ###
